### PR TITLE
add pom.xml

### PR DESCRIPTION
**Pull request by michaellilltokiwa**
In my tests compiling with:
`mvn -T 1C compile`: ~7s
`make build/bin/fz` : ~18s

### CODE REVIEW

**Comment by fridis** [comment]
This is an impressive speedup, but I do not understand where it comes from and for me .pom files are just gibberish that I do not understand, so I need help here. 
My experience with mvn so far was that it downloads tons of packages from all around the world and I completely lose control of what is happening. 
So the only blocking factor for this PR is my lack of understanding what mvn does and how to control it.

**Comment by michaellilltokiwa** [comment]
I could/should have explained that `-T 1C` means one thread per cpu core. So this uses all available cpu-cores when possible. This might be one reason why it is so much faster but this is just a guess since I also do not understand the maven magic.

**Comment by michaellilltokiwa** [comment]
@fridis @maxteufel I'm not sure what to do with this? My idea would be to keep `make` as the main build tool, but optionally have make use mvn for building java. But I'm not sure if it's worth the hassle of maintaining... What do you think?

**Comment by michaellilltokiwa** [comment]
@tokiwa-software/developers  Okay, let's stick with `make` then.

**Pull request closed without merging**
