### PR TITLE
adding error handling to the fileio.write feature

### PR DESCRIPTION
**Pull request by WaelYoussfi**
I am not sure whether I need to make the return type as outcome or just bool

### CODE REVIEW

**Comment by WaelYoussfi** [comment]
> I am not sure whether I need to make the return type as outcome or just bool

<outcome unit> made more sense than returning true in case of success and error in case of failure

**Comment by michaellilltokiwa** [comment]
what about `option error`?

**Comment by michaellilltokiwa** [comment]
@WaelYoussfi `outcome unit` and `option error` functionally are the same thing. i think it comes down to taste. which conveys better what you want to return. maybe outcome is better since you use this in other places as well so this would be more consistent.

**Comment by fridis** [comment]
IMHO, `outcome unit` is the right type here, since the result is `unit` in case of success. `option error` would have the disadvantage that we get an asymmetry with i/o operation that return a value different than `unit`. 
We might (later) decide to introduce a new unit type called something like `success` and use `outcome success` instead, which would make the `match`-clause more readable.

**Comment by WaelYoussfi** [comment]
@michaellilltokiwa thanks for the clarification.
@fridis I think that `success` will be very helpful in case I actually want to return something other than `unit`.

**Comment by michaellilltokiwa** [comment]
@fridis @WaelYoussfi To me `success` seems to be a helpful unit-type feature. It's more clear than `outcome unit` and I assume this outweighs the downside of having yet another unit-type feature.

**Pull request merged**
